$:
  vscode:
    - services:
        - vscode
        - docker
      runner:
        cpus: 16
      docker:
        image: docker.cnb.cool/arsrna/dev-image/nodejs
      stages:
        - name: 安装依赖
          script: bun i

  push:
    sync_to_github:
      runner:
        cpus: 2
      services:
        - docker
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          imports:
            - https://cnb.cool/arsrna/env/-/blob/main/git.yaml
          settings:
            target_url: https://github.com/ArSrNa/web-prompter.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            git_email: "root@arsrna.cn"

    # eo-deploy:
    #   services:
    #     - docker
    #   runner:
    #     cpus: 16
    #   docker:
    #     image: node:24
    #   stages:
    #     - name: 安装bun
    #       script: npm i -g bun
    #     - name: 安装依赖
    #       script: bun i
    #     - name: 构建
    #       script: bun run build
    #     - name: eo deploy
    #       script: bun publish
